In [83]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline 

# features selection libraries
from sklearn.feature_selection import RFE
from sklearn import svm
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

#import libraries models
from sklearn import model_selection, metrics, grid_search
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import classification_report
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier

# Import training data 

CAUTION! when importing the file the arrays nummer which were previously the names of the rows are no in a column!(take a look at the table) So we have to adjust this for the test and training data!

In [2]:
x_train = pd.read_csv('../data/train_features.csv')
y_train = pd.read_csv('../data/train_labels.csv')

Correct columns and names of rows for train (will do test data later). For some reason when importing the saved x_train and y_trian data pandas puts the names of the rows in a seperate columns. Thus adding an additional column (see x and y train after importing it)

In [3]:
# rename rows of x_train
x_train = x_train.rename(columns= {'Unnamed: 0':'arrays'})

array = 0 
for i in x_train.arrays:
    x_train = x_train.rename(index = {array : i})
    array +=1
x_train = x_train.drop('arrays', axis =1)

# rename rows of y_train
y_train = y_train.rename(columns= {'Unnamed: 0':'arrays'})

array = 0 
for i in y_train.arrays:
    y_train = y_train.rename(index = {array : i})
    array +=1
y_train = y_train.drop('arrays', axis =1)

In [ ]:
#y_train['Subgroups'] = y_train['Subgroups'].map(lambda x: x.strip('"'))

# RFE feature selection 

Note, RFE features selection might take a couple of minutes when testing for multiple parameters. 

In the paper they SVM as estimator and uses different penalties for C
for the SVM estimator for optimization.
C penalties used: 0.25, 1, 4, 16, 64, 256

To find out which of these have the best score for feature selection I will make a for loop and define the score for each feature selection for the different C parameters.

I am not entirely sure about this..... it says so in the paper but to me it somehow feels odd to do hyperparameter selection on the estimator of RFE.... maybe discuss this in monday

## 8 features

### Which C penalties gives best score for features selection

In [85]:
# select best SVC c penalty for 8 features
c_range = [0.25, 1, 4, 16, 64, 256]
scores = []
for i in c_range:
    estimator = svm.SVC(kernel = 'linear', C=i)
    selector_8f = RFE(estimator, 8)
    selector_8f = selector_8f.fit(x_train,y_train.values.ravel())
    scores.append(selector_8f.score(x_train,y_train))


In [89]:
scores

[0.9875, 0.9875, 0.9875, 1.0, 1.0, 1.0]

### Use parameter with best score

Apperently from 16 onward the score was the highest namely 1.0 so I used 16 for the C parameter

In [164]:
# feature selection for 8 features with best C score(=16)
estimator = svm.SVC(kernel ='linear', C=16) # in the paper they used SVC as the estimator (see appendix)
selector_RFE8 = RFE(estimator, 8)
selector_RFE8 = selector_RFE8.fit(x_train,y_train.values.ravel())

Since the feature columns are label 0 to 2833 we can see which columns are selected by finding the TRUE items in selector_8f.support_. This command gives you an array with true or false. If the feature are that position was selected it is label true

In [139]:
#find selected features
selector_RFE8.get_support(indices = True)


array([ 771, 1062, 1655, 1677, 2030, 2184, 2213, 2750], dtype=int64)

In [140]:
x_train_RFE8 = selector_RFE8.transform(x_train)
x_train_RFE8.shape

(80, 8)

## 32 features

### Which C penalties gives best score for features selection

In [94]:
# select best SVC c penalty for 32 features
c_range = [0.25, 1, 4, 16, 64, 256]
scores = []
for i in c_range:
    estimator = svm.SVC(kernel = 'linear', C=i)
    selector_32f = RFE(estimator, 32)
    selector_32f = selector_32f.fit(x_train,y_train.values.ravel())
    scores.append(selector_32f.score(x_train,y_train))


In [96]:
scores

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

### Use parameter with best score


For this one all of them have a score of 1.0 so I'll use the default

In [165]:
# feature selection for 32 features for best C score(=)

estimator = svm.SVC(kernel ='linear')
selector_RFE32 = RFE(estimator, 32)
selector_RFE32 = selector_32f.fit(x_train,y_train.values.ravel())


In [143]:
#find selected features
selector_RFE32.get_support(indices = True)

array([ 190,  192,  226,  673,  762,  768,  771,  772,  854, 1035, 1062,
       1243, 1562, 1569, 1655, 1657, 1677, 1773, 1900, 1962, 2021, 2024,
       2030, 2079, 2125, 2183, 2184, 2213, 2214, 2548, 2655, 2750],
      dtype=int64)

In [144]:
x_train_RFE32 = selector_RFE32.transform(x_train)
x_train_RFE32.shape

(80, 32)

## 94 features

### Which C penalties gives best score for features selection

In [145]:
# select best SVC c penalty for 32 features
c_range = [0.25, 1, 4, 16, 64, 256]
scores = []
for i in c_range:
    estimator = svm.SVC(kernel = 'linear', C=i)
    selector_94f = RFE(estimator, 94)
    selector_94f = selector_94f.fit(x_train,y_train.values.ravel())
    scores.append(selector_94f.score(x_train,y_train))


In [146]:
scores

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

### Use parameter with best score


Again the score were all 1.0 so I took the default C

In [147]:
# feature selection for 94 features for best C score(=)
estimator = svm.SVC(kernel ='linear')
selector_RFE94 = RFE(estimator, 94)
selector_RFE94 = selector_RFE94.fit(x_train,y_train.values.ravel())
selector_RFE94.get_support(indices = True)


array([  41,  190,  192,  194,  226,  262,  463,  486,  672,  673,  762,
        765,  768,  769,  771,  772,  792,  849,  854,  855,  998,  999,
       1009, 1032, 1035, 1062, 1111, 1114, 1243, 1244, 1245, 1352, 1401,
       1561, 1562, 1569, 1596, 1655, 1657, 1663, 1677, 1773, 1812, 1817,
       1870, 1876, 1900, 1902, 1960, 1962, 1971, 1972, 2019, 2021, 2024,
       2029, 2030, 2032, 2056, 2068, 2070, 2078, 2079, 2125, 2126, 2182,
       2183, 2184, 2185, 2186, 2202, 2206, 2207, 2210, 2213, 2214, 2217,
       2218, 2515, 2528, 2547, 2548, 2549, 2655, 2734, 2748, 2749, 2750,
       2752, 2760, 2770, 2771, 2816, 2826], dtype=int64)

In [148]:
# feature selection for 32 features
selector_RFE94.get_support(indices = True)

array([  41,  190,  192,  194,  226,  262,  463,  486,  672,  673,  762,
        765,  768,  769,  771,  772,  792,  849,  854,  855,  998,  999,
       1009, 1032, 1035, 1062, 1111, 1114, 1243, 1244, 1245, 1352, 1401,
       1561, 1562, 1569, 1596, 1655, 1657, 1663, 1677, 1773, 1812, 1817,
       1870, 1876, 1900, 1902, 1960, 1962, 1971, 1972, 2019, 2021, 2024,
       2029, 2030, 2032, 2056, 2068, 2070, 2078, 2079, 2125, 2126, 2182,
       2183, 2184, 2185, 2186, 2202, 2206, 2207, 2210, 2213, 2214, 2217,
       2218, 2515, 2528, 2547, 2548, 2549, 2655, 2734, 2748, 2749, 2750,
       2752, 2760, 2770, 2771, 2816, 2826], dtype=int64)

In [149]:
x_train_RFE94 = selector_RFE94.transform(x_train)
x_train_RFE94.shape

(80, 94)

# ANOVA feature selection

 This methode does feature selection using univariate statistics. See http://scikit-learn.org/stable/modules/feature_selection.html for more info.
In this case I used f_classif, which makes the selector use ANOVA to select the best K features of the model.

In the paper no parameter selection was done for ANOVA

## 8 features

In [150]:
# feature selection for 8 features ANOVA
selector_ANOVA8= SelectKBest(f_classif, k=8).fit(x_train,y_train.values.ravel())
x_train_ANOVA8 = selector_ANOVA8.transform(x_train)
x_train_ANOVA8.shape

(80, 8)

In [151]:
selector.get_support(indices=True)

array([ 461,  463,  464,  672,  673,  819,  837,  839,  840,  842,  843,
        844,  845,  846,  847,  848,  849,  850,  851,  852,  853,  854,
        855,  856,  857,  861,  999, 1000, 1001, 1002, 1004, 1642, 1643,
       1645, 1646, 1647, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1659,
       1660, 1662, 1663, 1664, 1665, 1667, 1668, 1669, 1670, 1671, 1672,
       1673, 1674, 1676, 1677, 1678, 1679, 1687, 1971, 1972, 1973, 2019,
       2020, 2021, 2022, 2023, 2024, 2026, 2027, 2028, 2029, 2032, 2033,
       2034, 2035, 2036, 2038, 2039, 2040, 2184, 2206, 2207, 2210, 2213,
       2214, 2223, 2748, 2749, 2750, 2751], dtype=int64)

## 32 features

In [152]:
# feature selection for 32 features ANOVA
selector_ANOVA32= SelectKBest(f_classif, k=32).fit(x_train,y_train.values.ravel())
x_train_ANOVA32 = selector_ANOVA32.transform(x_train)
x_train_ANOVA32.shape

(80, 32)

In [153]:
selector.get_support(indices=True)

array([ 461,  463,  464,  672,  673,  819,  837,  839,  840,  842,  843,
        844,  845,  846,  847,  848,  849,  850,  851,  852,  853,  854,
        855,  856,  857,  861,  999, 1000, 1001, 1002, 1004, 1642, 1643,
       1645, 1646, 1647, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1659,
       1660, 1662, 1663, 1664, 1665, 1667, 1668, 1669, 1670, 1671, 1672,
       1673, 1674, 1676, 1677, 1678, 1679, 1687, 1971, 1972, 1973, 2019,
       2020, 2021, 2022, 2023, 2024, 2026, 2027, 2028, 2029, 2032, 2033,
       2034, 2035, 2036, 2038, 2039, 2040, 2184, 2206, 2207, 2210, 2213,
       2214, 2223, 2748, 2749, 2750, 2751], dtype=int64)

## 94 features

In [154]:
# feature selection for 94 features ANOVA
selector_ANOVA94= SelectKBest(f_classif, k=94).fit(x_train,y_train.values.ravel())
x_train_ANOVA94 = selector_ANOVA94.transform(x_train)

In [155]:
selector.get_support(indices=True)

array([ 461,  463,  464,  672,  673,  819,  837,  839,  840,  842,  843,
        844,  845,  846,  847,  848,  849,  850,  851,  852,  853,  854,
        855,  856,  857,  861,  999, 1000, 1001, 1002, 1004, 1642, 1643,
       1645, 1646, 1647, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1659,
       1660, 1662, 1663, 1664, 1665, 1667, 1668, 1669, 1670, 1671, 1672,
       1673, 1674, 1676, 1677, 1678, 1679, 1687, 1971, 1972, 1973, 2019,
       2020, 2021, 2022, 2023, 2024, 2026, 2027, 2028, 2029, 2032, 2033,
       2034, 2035, 2036, 2038, 2039, 2040, 2184, 2206, 2207, 2210, 2213,
       2214, 2223, 2748, 2749, 2750, 2751], dtype=int64)

# Classification methodes

## KNN (K-Nearest-Neighbor)

First we want to do hyperparameter optimization. in the paper they optimize for: k_neighbors, Distance function and weight function

In [112]:
knn = KNeighborsClassifier()
# define the parameter range that should be searched
k_range = list(range(1, 31))
dist_func = [1,2]# 1 = manhattan, 2= Euclidean
dist_weight = ['uniform', 'distance']

# create a parameter grid: map the parameter names to the values that should be searched
param_grid = dict(n_neighbors=k_range, p=dist_func,weights=dist_weight)

# instantiate the grid
grid_search= GridSearchCV(knn, param_grid, cv=10, scoring='accuracy')

### Fit parameters for all features RFE

In [119]:

# 8 features
grid_RFE8 = grid_search.fit(x_train_RFE8, y_train.values.ravel())
print('Best score for 8 features:',grid_search.best_score_)
print('Best parameters for 8 features:',grid_search.best_params_)

# 32 features
grid_RFE32 = grid_search.fit(x_train_RFE32, y_train.values.ravel())
print('Best score for 32 features:',grid_search.best_score_)
print('Best parameters for 32 features:',grid_search.best_params_)

# 94 features
grid_RFE94 = grid_search.fit(x_train_RFE94, y_train.values.ravel())
print('Best score for 94 features:',grid_search.best_score_)
print('Best parameters for 94 features:',grid_search.best_params_)


Best score for 8 features: 0.95
Best parameters for 8 features: {'n_neighbors': 16, 'p': 2, 'weights': 'distance'}
Best score for 32 features: 0.9625
Best parameters for 32 features: {'n_neighbors': 11, 'p': 2, 'weights': 'distance'}
Best score for 94 features: 0.875
Best parameters for 94 features: {'n_neighbors': 10, 'p': 2, 'weights': 'distance'}


For 8 features the best outcome was: k = 16 | p = euclidean distance | weights = distance

For 32 features the best outcome was: k = 11 | p = euclidean distance | weights = distance

For 94 features the best outcome was: k = 10 | p = euclidean distance | weights = distance


### Fit parameters for all features ANOVA

In [121]:
# 8 features
grid_ANOVA8 = grid_search.fit(x_train_ANOVA8, y_train.values.ravel())
print('Best score for 8 features:',grid_search.best_score_)
print('Best parameters for 8 features:',grid_search.best_params_)

# 32 features
grid_ANOVA32 = grid_search.fit(x_train_ANOVA32, y_train.values.ravel())
print('Best score for 32 features:',grid_search.best_score_)
print('Best parameters for 32 features:',grid_search.best_params_)

# 94 features
grid_ANOVA94 = grid_search.fit(x_train_ANOVA94, y_train.values.ravel())
print('Best score for 94 features:',grid_search.best_score_)
print('Best parameters for 94 features:',grid_search.best_params_)

Best score for 8 features: 0.8375
Best parameters for 8 features: {'n_neighbors': 15, 'p': 2, 'weights': 'distance'}
Best score for 32 features: 0.8625
Best parameters for 32 features: {'n_neighbors': 6, 'p': 2, 'weights': 'uniform'}
Best score for 94 features: 0.8375
Best parameters for 94 features: {'n_neighbors': 8, 'p': 2, 'weights': 'distance'}


For 8 features the best outcome was: k = 15 | p = euclidean distance | weights = distance

For 32 features the best outcome was: k = 6 | p = euclidean distance | weights = uniform

For 94 features the best outcome was: k = 8 | p = euclidean distance | weights = distance

## Make knn models

### RFE models

In [226]:
#8 features 
knn_model_RFE8 = KNeighborsClassifier(n_neighbors = 16, p = 2, weights = 'distance')
knn_model_RFE8.fit(x_train_RFE8,y_train.values.ravel())

#32 features 
knn_model_RFE32 = KNeighborsClassifier(n_neighbors = 11, p = 2, weights = 'distance')
knn_model_RFE32.fit(x_train_RFE32,y_train.values.ravel())

#94 features 
knn_model_RFE94 = KNeighborsClassifier(n_neighbors = 10, p = 2, weights = 'distance')
knn_model_RFE94.fit(x_train_RFE94,y_train.values.ravel())

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=10, p=2,
           weights='distance')

AttributeError: 'KNeighborsClassifier' object has no attribute 'shape'

### ANOVA models

In [216]:
#8 features 
knn_model_ANOVA8 = KNeighborsClassifier(n_neighbors = 15, p = 2, weights = 'distance')
knn_model_ANOVA8.fit(x_train_ANOVA8,y_train.values.ravel())

#32 features 
knn_model_ANOVA32 = KNeighborsClassifier(n_neighbors = 6, p = 2, weights = 'uniform')
knn_model_ANOVA32.fit(x_train_ANOVA32,y_train.values.ravel())

#94 features 
knn_model_ANOVA94 = KNeighborsClassifier(n_neighbors = 8, p = 2, weights = 'distance')
knn_model_ANOVA94.fit(x_train_ANOVA94,y_train.values.ravel())

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=8, p=2,
           weights='distance')

# Predict y_test

### Import test set

In [126]:
x_test = pd.read_csv('../data/test_features.csv')
y_test = pd.read_csv('../data/test_labels.csv')

In [129]:
# rename rows of x_train
x_test = x_test.rename(columns= {'Unnamed: 0':'arrays'})

array = 0 
for i in x_test.arrays:
    x_test = x_test.rename(index = {array : i})
    array +=1
x_test = x_test.drop('arrays', axis =1)

# rename rows of y_train
y_test = y_test.rename(columns= {'Unnamed: 0':'arrays'})

array = 0 
for i in y_test.arrays:
    y_test = y_test.rename(index = {array : i})
    array +=1
y_test = y_test.drop('arrays', axis =1)

### Take selected features per selection methode from test data

### RFE

In [208]:
# x_test for 8 features RFE
x_test_RFE8 = x_test[x_test.columns[selector_RFE8.get_support(indices = True)]]
# x_test for 32 features
x_test_RFE32 = x_test[x_test.columns[selector_RFE32.get_support(indices = True)]]
# x_test for 94 features
x_test_RFE94 = x_test[x_test.columns[selector_RFE94.get_support(indices = True)]]

print(x_test_RFE8.shape)
print(x_test_RFE32.shape)
print(x_test_RFE94.shape)


(20, 8)
(20, 32)
(20, 94)


### ANOVA

In [209]:
# x_test for 8 features ANOVA
x_test_ANOVA8 = x_test[x_test.columns[selector_ANOVA8.get_support(indices = True)]]
# x_test for 32 features
x_test_ANOVA32 = x_test[x_test.columns[selector_ANOVA32.get_support(indices = True)]]
# x_test for 94 features
x_test_ANOVA94 = x_test[x_test.columns[selector_ANOVA94.get_support(indices = True)]]

print(x_test_RFE8.shape)
print(x_test_RFE32.shape)
print(x_test_RFE94.shape)

(20, 8)
(20, 32)
(20, 94)


### Prediction RFE (STILL HAVE TO DO THIS FOR TEST DATA!!!)

In [228]:
# 8 features
y_predict_RFE8 = knn_model_RFE8.predict(x_train_RFE8) # will do for test data
print('accuracy for 8 feature RFE: ',metrics.accuracy_score(y_train, y_predict_RFE8))
# 32 features
y_predict_RFE32 = knn_model_RFE32.predict(x_train_RFE32) # will do for test data
print('accuracy for 32 features RFE: ',metrics.accuracy_score(y_train, y_predict_RFE32))
# 94 features
y_predict_RFE94 = knn_model_RFE94.predict(x_train_RFE94) # will do for test data
print('accuracy for 94 features RFE: ',metrics.accuracy_score(y_train, y_predict_RFE94))


accuracy for 8 feature RFE:  1.0
accuracy for 32 features RFE:  1.0
accuracy for 94 features RFE:  1.0


### Prediction ANOVA (STILL HAVE TO DO THIS FOR TEST DATA!!!)

In [229]:
# 8 features
y_predict_ANOVA8 = knn_model_ANOVA8.predict(x_train_ANOVA8) # will do for test data
print('accuracy for 8 feature ANOVA: ',metrics.accuracy_score(y_train, y_predict_ANOVA8))
# 32 features
y_predict_ANOVA32 = knn_model_ANOVA32.predict(x_train_ANOVA32) # will do for test data
print('accuracy for 32 features ANOVA: ',metrics.accuracy_score(y_train, y_predict_ANOVA32))
# 94 features
y_predict_ANOVA94 = knn_model_ANOVA94.predict(x_train_ANOVA94) # will do for test data
print('accuracy for 94 features ANOVA: ',metrics.accuracy_score(y_train, y_predict_ANOVA94))

accuracy for 8 feature ANOVA:  0.8875
accuracy for 32 features ANOVA:  0.9
accuracy for 94 features ANOVA:  1.0
